#9 add automated testing of basic cases
DARMA-tasking/ccm-milp pull request #11
Opened 2024-09-09 13:20 UTC by maxime-bfsquall

resolve #9 

Reviews the code to separete each class for more modularity
Create of two scripts 'ccm-milp_problem.py' and 'ccm_milp_solver.py' to seperate functionnalities
Review code to be pylint compliant
Add "Code Quality" into the CI: 
- Thanks to Tox, a script is launched to test all the examples with 3 differents solvers (PULP_CBC_CMD, COIN_CMD and GLPK_CMD)
- Add pylint test
- Report test results

2024-09-09 15:31 UTC, ppebay requested changes

2024-09-09 15:31 UTC, ppebay commented on examples/illustration_1.py
What we really want at this stage is to use the existing `SyntheticBlock` cases -- no other examples needed at this point -- , and to test it with a variety of configurations, in particular:
- load-only (COMCP) alon
- load-only + cluster-preserving
- load-only + memory bound
- FWMP with alpha = 1, all other coeffs at 0, which should amount to exactly the same results as above
- FWMP with alpha =1 and some non zero values of beta, gamma, delta

Ideally this should be synchronized with what has already been done to test LBAF, for the same case, with @cwschilly

2024-09-10 08:53 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
Are you sure that the optimal value found in this case isn't 2.5 (instead of 2.0)?

2024-09-10 08:53 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                        'file': '1-fwmp-with-alpha-beta.yaml',
What is this case testing exactly with `beta`?

2024-09-10 09:57 UTC, maxime-bfsquall commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
Maybe my understanding of the configuration is wrong.

Yes, we found **2.0** with the current configuration : 
`is_fwmp: False
alpha: 0
beta: 0
gamma: 0
delta: 0
bounded_memory: False
preserve_clusters: True`

We found **0.0** when we set is_fwmp to True:
`is_fwmp: True
alpha: 0
beta: 0
gamma: 0
delta: 0
bounded_memory: False
preserve_clusters: True`

We found **2.5** when we set is_fwmp to True and alpha to 1: 
`is_fwmp: True
alpha: 1
beta: 0
gamma: 0
delta: 0
bounded_memory: False
preserve_clusters: True`

2024-09-10 10:06 UTC, maxime-bfsquall commented on src/CcmMilp/Configuration.py
> +                        'file': '1-fwmp-with-alpha-beta.yaml',
I just reviewed the configuration, it tests: 
`is_fwmp: True
alpha: 1
beta: 1
gamma: 0
delta: 0
bounded_memory: False
preserve_clusters: False`

And the objective value found is 4.0

2024-09-10 11:21 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
A bug was introduced, because it is **not** possible to find 2.0 when clusters are preserved.  It seems that the value of `True` for `preserve_clusters` is not used with this version of the code. We need to look into this.

When `preserve_clusters` is `True` we cannot achieve anything better than 2.5 with the COMCP (FWMP=`False`) model.

2024-09-10 11:36 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
@maxime-bfsquall I know what happened! I introduced an incorrect indentation in the previous branch that got merged (and because I did not manually test the COMCP I did not notice it!):
<img width="746" alt="Screenshot 2024-09-10 at 07 32 36" src="https://github.com/user-attachments/assets/108e8145-285b-4149-9e57-810e27390438">

BTW this is a major flaw a Python, this dependency on indentation (which I had  criticized from the first day when I discovered that language almost 2 decades ago!)

I am pushing the fix as part of this branch.

So, please note:
- you should now find 2.5 for this case
- when running in COMCP mode (i.e. when FWMP is set to `False`) you do **not** need to set the values of the `alpha`, `beta`, `gamma`, and `delta` coefficients, as those are automatically set to 1, 0, 0, and 0 automatically.

2024-09-10 11:47 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
@maxime-bfsquall I pushed the correction and I confirm that the results are now correct in `COMCP` mode as well:

<img width="498" alt="Screenshot 2024-09-10 at 07 44 41" src="https://github.com/user-attachments/assets/2eb90b15-2922-486f-8f65-0b2427645717">

So for this case the parameters should be as follows:
```
is_fwmp: False bounded_memory: False preserve_clusters: True
```
and the computed optimum should be **2.5**.

It will therefore match the correct result of **2.5** that you are already finding for the full model with these parameters:
```
is_fwmp: True alpha: 1 beta: 0 gamma: 0 delta: 0 bounded_memory: False preserve_clusters: True
```
as it is exactly the same, as the COMCP example above.

2024-09-10 12:21 UTC, maxime-bfsquall commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
I changed the objective value to the expected value **2.5** for "load-only + cluster-preserving"
I also removed the coefficient values ​​in the test configuration when their value matches the default

2024-09-10 12:35 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
Alright, so here is now the other case that I wanted to discuss:
```
is_fwmp: True alpha: 0 beta: 0 gamma: 0 delta: 0 bounded_memory: False preserve_clusters: True
```
for this case you mentioned that you were finding 0.0, which is technically correct -- but it's not surprising indeed, as it amounts to a combination that is always equal to 0. Therefore, the optimum can only be 0!

At first glance I wanted to ask you to remove this case, but after having thought a bit more about it, I think it's best to keep it, but just to give it a different name, e.g., `null-case`. It's better to test this corner case as well.

That being said, we should then **also** test the following case
```
is_fwmp: True alpha: 1.0 beta: 0.0 gamma: 0.0 delta: 0.0 bounded_memory: False preserve_clusters: False
```
and make sure that find **2.0**. This is to verify that this FWMP, which is equivalent to the simplest COMCP case, also reports a correct value.

2024-09-10 13:36 UTC, maxime-bfsquall commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
I added `null-case` into the test process.

The case :  
`is_fwmp: True alpha: 1.0 beta: 0.0 gamma: 0.0 delta: 0.0 bounded_memory: False preserve_clusters: False` 
is already tested under the config 'fwmp-with-alpha'

2024-09-10 13:38 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                            'Optimal - objective value 2.00000000',
Ok great, resolving this conversation. Thanks @maxime-bfsquall

2024-09-10 14:32 UTC, ppebay commented on src/CcmMilp/Configuration.py
> +                        'file': '1-fwmp-with-alpha-beta.yaml',
Alright @maxime-bfsquall before testing the example your mentioned above (which combines the **compute** (`alpha`) and **off-node communication** (`beta`) terms, let's first make sure that we correctly resolve the latter only (`beta`). Can you thus please add the following `off-node-communication-only` case:
```
is_fwmp: True alpha: 0.0 beta: 1.0 gamma: 0.0 delta: 0.0 bounded_memory: False preserve_clusters: False
```
and make sure that we find the following optimum: **0.0**?

Thanks

2024-09-10 15:43 UTC, ppebay requested changes

2024-09-10 15:43 UTC, ppebay commented on src/CcmMilp/Configuration.py
Please rename this directory name **not** using mixed/camel case as it's not consistent with the fact that these are all initials.
I think we could use either `CCM_MILP` or `ccm_milp`

2024-09-10 15:43 UTC, ppebay commented on src/CcmMilp/Generator.py
Please do not capitalize Python file names; use `generator.py` instead. Same remark for all other Python files here.

2024-09-12 11:27 UTC, ppebay requested changes

2024-09-12 11:27 UTC, ppebay commented on README.md
Can you please an `## Expected Results:` section, providing a bulleted-list of all the cases that are currently in CI, with:
* their configurations (i.e. `FWMP=False, preserve_clusters=False` etc.
* their expected correct optimization results

This is for ease of comparison with temperedLB & LBAF.

2024-09-12 11:27 UTC, ppebay commented on examples/data/illustration_1.py
Why is this called called `illustration_1`? Does it correspond to a know case (or published elsewhere)?

2024-09-12 11:27 UTC, ppebay commented on src/ccm_milp/configuration.py
Would there be a different way to implement this, so GitHub does not complain with the "too few public methods" nonsensical style warning?

2024-09-12 11:27 UTC, ppebay commented on src/ccm_milp/generator.py
> +        self_i = self.i
What is the point of using these `self_` local variables? Why not use the `self.` member variables?

2024-09-12 11:27 UTC, ppebay commented on tests/config/1-load-only.yaml
Please make sure to add also the COMCP case (`is_fwmp: False`) with `preserve_clusters` set to `True` also. Expected value is 2.5

2024-09-12 11:44 UTC, maxime-bfsquall commented on src/ccm_milp/generator.py
> +        self_i = self.i
I removed them and use `self` instead.
I had changed the variable names to be pylint compliant and had not remove them because I had not checked if these variables were modified in the algorithm

2024-09-12 11:49 UTC, maxime-bfsquall commented on tests/config/1-load-only.yaml
Yes, it is (1-load-only-and-cluster.yml)

2024-09-12 12:27 UTC, maxime-bfsquall commented on examples/data/illustration_1.py
This example was already here when I started. Maybe @tlamonthezie can help to understand ?

2024-09-12 13:46 UTC, maxime-bfsquall commented on src/ccm_milp/configuration.py
We can disable these messages globally or on a specific code using comments

2024-09-12 14:09 UTC, ppebay requested changes
Only minuscule changes requested now, this is almost complete

2024-09-12 14:09 UTC, ppebay commented on README.md
> +* Fwmp with alpha
Please capitalize (FWMP)

2024-09-12 14:09 UTC, ppebay commented on examples/data/illustration_1.py
No big deal, we can discuss at meeting, resolving. Thanks

2024-09-12 14:09 UTC, ppebay commented on src/ccm_milp/configuration.py
Yes but I would rather not disable them, if there is a way to genuinely improve the code (as in: make it more Pythonic)

2024-09-12 14:11 UTC, maxime-bfsquall commented on README.md
This section was added at the end of the README

2024-09-13 12:53 UTC, ppebay approved these changes
We have converged! Thanks @maxime-bfsquall

2024-09-13 13:26 UTC, merged