#25: Add support for node-level memory constraints
DARMA-tasking/ccm-milp pull request #30
Opened 2024-11-16 22:48 UTC by ppebay

Resolves #25

2024-11-16 22:49 UTC, ppebay commented
@pierrepebay can you please look into the CI issues? Thanks

2024-11-17 16:19 UTC, ppebay commented
@lifflander @pierrepebay all issues fixed, PR can now be reviewed tx

2024-11-18 10:03 UTC, pierrepebay commented on src/ccm_milp_parse_json.py
> +        description="Parse json data to a python class oused by problem solver")
"oused" => "used"

2024-11-18 16:14 UTC, lifflander requested changes
Overall, this looks good to me. I just see an issue with the parser, it should be `shared_id`, not `shared_block_id`

2024-11-18 16:14 UTC, lifflander commented on src/ccm_milp/data.py
> +                        shared_block_id = task.get("user_defined").get("shared_block_id")
This is not correct. It is `shared_id` in the json files.

2024-11-18 16:21 UTC, ppebay commented on src/ccm_milp/data.py
> +                        shared_block_id = task.get("user_defined").get("shared_block_id")
The problem is that we use `shared_id` then we get an error with the data files stored in CCM-MILP (the block IDs get disregarded).

Could it be that the data files there are themselves outdated?

2024-11-19 10:35 UTC, ppebay commented on src/ccm_milp/data.py
> +                        shared_block_id = task.get("user_defined").get("shared_block_id")
@lifflander after having spoken about the issue @pierrepebay I realized that the data files in `ccm-milp` were, in fact, outdated as they use the `shared_block_id` key that has been deprecated elsewhere. I am therefore copying the more recent data set from `LBAF` and subsequently reverting `data.py` from `shared_block_id` to `shared_id`.
That should resolve the issue. Tx

2024-11-19 20:27 UTC, merged